package com.karoliinamultas.bluetoothchat.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFA13B48)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDADB)
val md_theme_light_onPrimaryContainer = Color(0xFF40000D)
val md_theme_light_secondary = Color(0xFF765658)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDADB)
val md_theme_light_onSecondaryContainer = Color(0xFF2C1517)
val md_theme_light_tertiary = Color(0xFF9F3C52)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9DD)
val md_theme_light_onTertiaryContainer = Color(0xFF400014)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1A)
val md_theme_light_surface = Color(0xFFEDEFEF)
val md_theme_light_onSurface = Color(0xFF201A1A)
val md_theme_light_surfaceVariant = Color(0xFFF4DDDD)
val md_theme_light_onSurfaceVariant = Color(0xFF524344)
val md_theme_light_outline = Color(0xFF857373)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEED)
val md_theme_light_inverseSurface = Color(0xFF362F2F)
val md_theme_light_inversePrimary = Color(0xFFFFB2B7)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFA13B48)
val md_theme_light_outlineVariant = Color(0xFFD7C1C2)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF8B635C)
val md_theme_dark_onPrimary = Color(0xFF630B1D)
val md_theme_dark_primaryContainer = Color(0xFF822432)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDADB)
val md_theme_dark_secondary = Color(0xFFE6BDBE)
val md_theme_dark_onSecondary = Color(0xFF44292B)
val md_theme_dark_secondaryContainer = Color(0xFF5C3F41)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDADB)
val md_theme_dark_tertiary = Color(0xFFFFB2BD)
val md_theme_dark_onTertiary = Color(0xFF620B26)
val md_theme_dark_tertiaryContainer = Color(0xFF80243C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9DD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF242124)
val md_theme_dark_onBackground = Color(0xFFF5FEFD)
val md_theme_dark_surface = Color(0xFF26282A)
val md_theme_dark_onSurface = Color(0xFFECE0DF)
val md_theme_dark_surfaceVariant = Color(0xFF524344)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C2)
val md_theme_dark_outline = Color(0xFF9F8C8D)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1A)
val md_theme_dark_inverseSurface = Color(0xFFECE0DF)
val md_theme_dark_inversePrimary = Color(0xFFA13B48)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB2B7)
val md_theme_dark_outlineVariant = Color(0xFF524344)
val md_theme_dark_scrim = Color(0xFF000000)


//Background ja chattekstit
//Light
val bgl1 = Color(0xFFD5DCF9)
val bgl2 = Color(0xFFEFE6DD)
val bgl3 = Color(0xFFB7B6C1)
val bgl4 = Color(0xFFD5CFE1)
val bgl5 = Color(0xFFEDDFEF)

val tl1 = Color(0xFF00FDDC)
val tl2 = Color(0xFFFF729F)
val tl3 = Color(0xFF04E762)
val tl4 = Color(0xFF208AAE)
val tl5 = Color(0xFFFF4365)

//Dark
val bgd1 = Color(0xFF111D4A)
val bgd2 = Color(0xFF43AA8B)
val bgd3 = Color(0xFF8B635C)
val bgd4 = Color(0xFF60594D)
val bgd5 = Color(0xFF93A29B)

val td1 = Color(0xFFE28413)
val td2 = Color(0xFF9E2B25)
val td3 = Color(0xFFD9FFF8)
val td4 = Color(0xFFFDE74C)
val td5 = Color(0xFFBA7BA1)



val seed = Color(0xFFBE515D)